# Generated by Django 2.2.5 on 2019-10-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_od_birth',
            new_name='date_of_birth',
        ),
    ]
